MEASURE_TEMPERATURE = 'MEASURE_TEMPERATURE'
MEASURE_HUMIDITY = 'MEASURE_HUMIDITY'
MEASURE_CO2 = 'MEASURE_CO2'

SET_TEMPERATURE = 'SET_TEMPERATURE'
SET_HUMIDITY = 'SET_HUMIDITY'
SET_LIGHTING = 'SET_LIGHTING'
SET_CO2 = 'SET_CO2'

FLIP_SCENARIO = 'FLIP_SCENARIO'
